devjeans-si-d/Si-D-client

src/components/modal/ModalComponent.vue, src/components/modal/ModalView.vue
모달창 컴포넌트 생성했습니다.
테스트 코드는 ModalView 코드로 만들어뒀습니다!
(아래 결과화면은 home에서 하고 다시 지웠습니다!)
- 모달창 열리기 전
- 모달창 열림
- 모달창 확인 버튼 클릭 시 함수 실행
해당 모달창은 회원가입 등에 쓰일 모달창입니다.
project/lauchedProject에서 쓰일 회원 검색 모달창은 검색 API 배우고 나서 생성하겠습니다!
feat/IS-34
=> feat: ModalComponent 초안

src/components/navbar/PageNavbar.vue, src/components/test/HeaderComponent.vue, src/components/title/PageTitleComponent.vue, src/views/member/ChattingList.vue, src/views/member/MyPage.vue, src/views/member/MyPageEdit.vue
=> feat/IS-40: 마이페이지, 회원 정보 수정

src/components/card/ProjectApplyComponent.vue, src/components/card/ProjectManagementComponent.vue, src/components/card/ProjectScrapComponent.vue, src/components/chip/BasicSmallChip.vue, src/components/navbar/ProjectSidebar.vue, src/router/memberRouter.js, src/views/member/ChattingList.vue, src/views/member/MyApply.vue, src/views/member/MyPage.vue, src/views/member/MyPageEdit.vue, src/views/member/MyScrap.vue
내가 참여한 프로젝트, 지원한 프로젝트, 스크랩 페이지
배치가 예쁘지 않다는 것을 알고있습니다..
하지만 너무 시간을 많이 써서 api 붙이면서 교정을 해보겠습니다
=> feat/IS-44: 내가 참여한 프로젝트, 지원한 프로젝트, 스크랩 페이지

src/components/modal/ProjectMembersComponent.vue, src/components/modal/TechStackSelector.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue, src/views/project/ProjectCreate.vue
Project Create 화면 스타일 수정, TechStackSelector 스타일 수정, ProjectMembersComponent 추가
feat/IS-57
=> Feat/is-57 :  Project Create 화면 스타일 수정, TechStackSelector 스타일 수정, ProjectMembersComponent 추가

src/router/projectRouter.js, src/views/project/ProjectCreate.vue, src/views/project/ProjectList.vue
=> feat/IS-61 : 프로젝트 생성 페이지 오류 수정

package-lock.json, package.json, src/components/modal/TechStackSelector.vue, src/router/LaunchedProjectRouter.js, src/router/projectRouter.js, src/views/LaunchedProject/LaunchedProjectEdit.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue, src/views/LaunchedProject/LaunchedProjectView.vue, src/views/project/ProjectCreate.vue, src/views/project/ProjectEdit.vue, src/views/project/ProjectView.vue
- 프로젝트 생성 ( /project-create )
- 프로젝트 수정 ( /project-edit/{id} )
- 프로젝트 상세  (/project/{id} )
- 완성된 프로젝트 생성 ( /launched-project/register/:projectId ) 
- 완성된 프로젝트 수정 ( /launched-project/:launchedProjectId/edit )
- 완성된 프로젝트 상세 ( /launched-project/:launchedProjectId )
- launched project에 에디터가 계속 안 들어가서 우선 text area로 했습니다!!
- 기술스택은 갓세호님을 기다립니다.
feat/IS-71
=> feat:IS-71: 프로젝트 CRU & 완성된 프로젝트 CRU 기능 추가

src/components/card/ChattingListComponent.vue, src/components/card/EnChatroomComponent.vue, src/components/card/EnChattingListComponent.vue, src/components/card/ProjectApplyComponent.vue, src/components/card/ProjectManagementComponent.vue, src/components/card/ProjectScrapComponent.vue, src/components/navbar/ApplyListBar.vue, src/components/navbar/PageNavbar.vue, src/components/navbar/ProjectSidebar.vue, src/views/member/ChatroomView.vue, src/views/member/ChattingList.vue, src/views/member/MyApply.vue, src/views/member/MyPage.vue, src/views/member/MyProject.vue, src/views/member/MyScrap.vue
=> feat/IS-67: 마이페이지들 페이지네이션 구현, 화면 이동 코드 추가, "내 프로젝트" 페이지에 버튼 추가

package-lock.json, package.json, src/components/modal/TechStackSelector.vue, src/main.js, src/store/index.js, src/store/techStack.js, src/views/siderCard/MySiderCard.vue, src/views/siderCard/SiderCard.vue, src/views/siderCard/SiderCardList.vue
- 기술스택 컴포넌트 vuex 적용
- requird에 따라 기술스택 선택 버튼 감추기
- 사이더카드 업데이트 기술스택 선택 적용
- 사이더카드 조회 기술스택 조회 적용
- 사이더카드 조회 기술 스택
- 사이더카드 업데이트 기술스택 선택
feat/IS-64
=> feat/IS-64: 기술스택 선택 컴포넌트 vuex 적용

src/components/modal/TechStackSelector.vue
=> refactor: 충돌해결

src/components/header/HeaderComponent.vue, src/components/modal/TechStackSelector.vue, src/components/windows/LaunchedProjectWindow.vue, src/views/MainPage/MainPage.vue
=> Feat/IS-74 : header 수정 (프로젝트 관리 추가)

src/views/LaunchedProject/LaunchedProjectEdit.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue
- 생성 시 이미지 url 잘 들어갑니다!
- 수정 시 이미지 url 잘 변경됩니다!
fix/IS-79
=> chore: 이미지 변수 수정

package-lock.json, src/views/siderCard/MySiderCard.vue, src/views/siderCard/SiderCard.vue
- 이제 사이더카드에서 출시한 프로젝트를 볼 수 있습니다
feat/IS-94
=> feat/IS-94: 사이더카드에서 출시한 프로젝트 조회

src/views/siderCard/SiderCard.vue
=> fix/IS-95: 사이더카드 재직중일 경우 처리

src/views/siderCard/SiderCardList.vue
- 사이더카드 목록 필터, 스크롤 페이지네이션 적용
feat/IS-96
=> feat/IS-96: 사이더카드 목록 필터, 스크롤 페이지네이션 적용

src/components/windows/LaunchedProjectWindow.vue, src/components/windows/ProjectWindow.vue, src/views/LaunchedProject/LaunchedProjectDetail.vue, src/views/LaunchedProject/LaunchedProjectList.vue, src/views/MainPage/MainPage.vue
- 완성된프로젝트 리스트 페이지네이션처리, 기술스택 필터링 기능 적용 
- 검색창, 출시된프로젝트만 보기 스위치 주석처리
feat/IS-92
=> feat/IS-92 feat : 완성된프로젝트 리스트 페이지네이션처리, 기술스택 필터링 기능 적용 + 검색창, 출시된프로젝트만 보기 스위치 주석처리

src/components/header/HeaderComponent.vue, src/views/member/MyAlert.vue
=> chore: alert 수정

package-lock.json, src/router/index.js, src/views/siderCard/MySiderCard.vue
=> feat/IS-98:  화면이동시 스크롤 상단으로 이동, 직무선택안할시 선택 강제

src/router/projectRouter.js, src/views/LaunchedProject/LaunchedProjectEdit.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue, src/views/LaunchedProject/LaunchedProjectView.vue, src/views/project/ProjectCreate.vue, src/views/project/ProjectCreate2.vue, src/views/project/ProjectEdit.vue, src/views/project/ProjectEdit2.vue, src/views/project/ProjectView2.vue, src/views/project/ProjectView3.vue
=> fix/IS-83: 프로젝트/완성된 프로젝트 생성/수정 

package-lock.json, package.json, src/views/project/ProjectCreate2.vue, src/views/project/ProjectEdit2.vue, src/views/project/ProjectView3.vue
- 데드라인 시간 인풋 및 모달창 제어
- 멤버 추가 없앰
- 모집 정보에서 pm 없앰
- 프로젝트 제목 유무 모달창 제어
fix/IS-102
=> fix/IS-102 : 프로젝트 생성 수정 관련 리뷰 반영

src/views/siderCard/MySiderCard.vue, src/views/siderCard/SiderCardList.vue
=> feat/IS-100: 사이더카드 이미지 수정 기능 추가

src/components/card/EnChatroomComponent.vue, src/components/card/EnChattingListComponent.vue, src/components/card/ProjectManagementComponent.vue
=> fix: 팀원으로 참여한 프로젝트 페이지네이션 수정

src/components/header/HeaderComponent.vue, src/components/oauth/OauthRedirect.vue, src/views/oauthLogin/SignUpPage.vue, src/views/siderCard/MySiderCard.vue, src/views/siderCard/SiderCard.vue
- 로그인시 사이더카드 수정 여부 묻기
- 사이더카드 디테일 에서 수정버튼 추가
- textarea 옵션 수정
- 완료한 프로젝트 이미지 크기 수정
feat/IS-104
=> feat/IS-104: 리뷰받은거 수정

src/components/modal/TechStackSelector.vue, src/components/oauth/OauthRedirect.vue, src/views/MainPage/MainPage.vue, src/views/siderCard/MySiderCard.vue
=> feat/IS-110: 사이더카드 경력, 기술스택 디자인 수정, 사이더카드 업데이트 요청 모달위치 메인으로 변경

src/views/siderCard/MySiderCard.vue, src/views/siderCard/SiderCard.vue
=> style: 사이더카드 조회 사용기술 스타일 수정

src/views/siderCard/SiderCardList.vue
=> fix/IS-112: 사이더카드 업데이트에서 조회로 이동시 스크롤 이벤트 발생하는 오류 수정

src/views/member/MyProject.vue, src/views/project/ProjectCreate2.vue
=> fix: 모집글 페이지

src/views/project/ProjectView5.vue
=> feat/IS-103 : project detail 수정

src/components/header/HeaderComponent.vue, src/views/member/MyAlert.vue
=> fix/IS-114: 알림 부분 수정

src/router/projectRouter.js, src/views/project/ProjectEdit2.vue, src/views/project/ProjectView5.vue
=> feat/IS-103 : 프로젝트 디테일 페이지 css 수정 및 기능 추가

src/views/LaunchedProject/LaunchedProjectEdit.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue, src/views/project/ProjectView5.vue
- launched project 수정/생성 시 디테일 페이지로 이동
- project view 화면 수정
feat/IS-103
=> feat/IS-103 : launched project 수정/생성 시 디테일 페이지로 이동 및 project view 화면 수정

src/views/project/ProjectView5.vue
=> feat/IS-103 : 프로젝트 디테일 폰트 색상 변경

src/views/project/ProjectEdit2.vue, src/views/project/ProjectView5.vue
=> feat/IS-103 : 복수 지원 방지 처리

src/views/project/ProjectView5.vue
- 프로젝트 지원현황 모집하는 것만 필터링
feat/IS-103
=> feat/IS-103 : project 지원 현황 모집하는 것만 보여주기

src/components/card/ProjectManagementComponent.vue
=> feat/IS-103 :프로젝트 관리 페이지 마감 추가

src/components/card/ProjectManagementComponent.vue, src/views/member/MyScrap.vue
=> feat: 모달, 알림 연결 성공

src/views/LaunchedProject/LaunchedProjectDetail.vue, src/views/LaunchedProject/LaunchedProjectList.vue, src/views/project/ProjectList.vue
…버튼 추가
프로젝트 글 작성 버튼 추가 ->  클릭 시 프로젝트 작성 글 path로 이동
fix/IS-121
=> fix : LaunchedProject조회화면 기술스택 태그 색깔적용 안되는 문제 수정, feat: 프로젝트 리스트에 글작성 버튼 추가

src/components/card/ProjectManagementComponent.vue
=> style: 버튼 디자인 변경

.env
=> chore: .env base url 변경

.env
=> chore: .env 변경

.env
=> chore: .env 삭제

src/components/header/HeaderComponent.vue, src/views/oauthLogin/LoginPage.vue, src/views/oauthLogin/SignUpPage.vue
=> chore: redirect uri 수정

src/components/test/HeaderComponent.vue, src/views/LaunchedProject/LaunchedProjectDetail.vue, src/views/project/ProjectView5.vue
=> chore/IS-127 : fix : 완성된 프로젝트 비로그인 상태 조회가능하도록 수정

src/views/LaunchedProject/LaunchedProjectEdit.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue, src/views/project/ProjectEdit2.vue, src/views/project/ProjectView5.vue
- 로그인 없이 project list 가능하게 수정 
- 로그인 없이 project detail 조회 가능하게 수정
- project list
- project detail : 스크랩, 채팅 신청, 지원 등의 버튼은 로그인 없이 안된다는 모달도 추가되었습니다.
fix/IS-129
=> fix/IS-129 : 로그인 없이 project list 및 detail 조회 가능하게 수정

src/views/LaunchedProject/LaunchedProjectEdit.vue, src/views/LaunchedProject/LaunchedProjectRegister.vue, src/views/project/ProjectEdit2.vue
- 프로젝트 update css 수정
- launched create&update css 수정
- project update  화면
- launched project create 화면
- launched project  update 화면
=> fix/IS-103: project launched create update css 수정

.github/workflows/deploy-fe-with-s3.yml, src/components/header/HeaderComponent.vue, src/views/oauthLogin/SignUpPage.vue
=> fix: redirect uri 수정

src/views/LaunchedProject/LaunchedProjectDetail.vue, src/views/LaunchedProject/LaunchedProjectList.vue, src/views/LaunchedProject/LaunchedProjectView.vue, src/views/MainPage/MainPage.vue
component import할때 태그 대소문자 구분해서 수정
=> chore: component 태그 대소문자구분

src/components/card/EnChatroomComponent.vue, src/views/member/ChatroomView.vue
=> chore: subscribe

src/views/member/MyAlert.vue
- my alert view  일자 및 시간 고침
fix/IS-141
=> fix/IS-141 : myalert view 일자 및 시간 고침

src/views/oauthLogin/SignUpPage.vue
=> fix/IS-141: signup 화면 수정

src/components/siderCard/CardComponent.vue, src/components/windows/SiderCardWindow.vue
=> fix : 메인페이지, SiderCard의 SiderCardComponent 스타일 수정

src/components/card/EnChatroomComponent.vue, src/views/member/ChatroomView.vue
=> fix: 채팅 가져오는 부분 수정

src/components/windows/LaunchedProjectWindow.vue, src/components/windows/SiderCardWindow.vue, src/views/LaunchedProject/LaunchedProjectList.vue
=> fix : LaunchedProjectWindow, SiderCardWindow, LaunchedProjectList CSS 수정

src/components/card/EnChattingListComponent.vue, src/views/member/ApplyManagement.vue, src/views/member/MyPage.vue, src/views/member/MyPageEdit.vue
=> fix/IS-149: 프론트 에러 수정

src/views/member/ApplyManagement.vue
=> fix: 지원서 글자 잘림 스크롤 추가

src/components/windows/SiderCardWindow.vue
=> fix : SiderCardWindow 스타일 수정

src/components/windows/SiderCardWindow.vue
=> fix : SiderCardWindow md=4로 수정

src/components/card/EnChatroomComponent.vue, src/views/member/ChattingList.vue
=> fix: enter chatroom 호출 시점 변경

src/views/project/ProjectView.vue
=> fix/IS-141 : 스크랩 수정

.github/workflows/deploy-with-s3.yml
=> chore : deploy 파일 dev -> www로 변경

src/views/project/ProjectView.vue
=> chore : ProjectView const=response 빼버려서 다시 추가

README.md
=> feat/IS-151 : readme 수정
